### ISSUE TITLE
Pavlos Triti

### ISSUE THREAD

**Issue by antokioukis** [antokioukis/evonet#5]
Prepei na eftia3e to sfg tou no_fit, logika an au3i8oun ta runs tote 8a pesei k allo ta kinks pou parousiazei

[sfs_oli_mera_pempti.pdf](https://github.com/antokioukis/evonet/files/658016/sfs_oli_mera_pempti.pdf)

Biologiko erwtima: pote simbainoun periptwseis substitution tou dominating atomou kai poso sixnes einai autes?

fitness
![childer](https://cloud.githubusercontent.com/assets/17062093/21275105/eaef4a4c-c3d3-11e6-89c7-338574d43b19.png)

neutral evolution
![children_no_fit](https://cloud.githubusercontent.com/assets/17062093/21275106/eaf2ead0-c3d3-11e6-88ab-3fab541aa85d.png)

**Comment by antokioukis** [comment]
to sensitivity array den einai auto pou 8eloume, prepei na to skeftoume

**Comment by idaios** [comment]
Πάρε subset gia to sfs. Gia paradeigma, 20 atomwn.
